services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
      - BACKEND_URL=https://80.87.98.111:8000
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - frontend-network

networks:
  default:
    name: shared-network
    external: true