services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "443:443"
    environment:
      - BACKEND_URL=https://album.pakulove.ru:8000
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - frontend-network

networks:
  frontend-network:
    driver: bridge 